import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { userIsStaff } from "@/lib/roles-server";
import { createAdminClient } from "@/lib/supabase/admin";
import { MAX_NOTICE_ATTACHMENTS, NOTICE_BUCKET, validatePdf } from "@/lib/notice-security";
import { sendNoticePushes } from "@/lib/push/send";
export const runtime = "nodejs";
async function staff(){const s=await createClient(); const {data:{user}}=await s.auth.getUser(); if(!user)return{e:NextResponse.json({error:"로그인이 필요합니다."},{status:401})}; if(!(await userIsStaff(s, user.id)))return{e:NextResponse.json({error:"교사 또는 관리자 권한이 필요합니다."},{status:403})}; return{user};}
export async function POST(req:Request){const a=await staff(); if("e" in a)return a.e; const b=await req.json(); const files=Array.isArray(b.attachments)?b.attachments:[]; if(files.length>MAX_NOTICE_ATTACHMENTS)return NextResponse.json({error:"PDF는 최대 5개까지 첨부할 수 있습니다."},{status:400}); if(!b.title?.trim()||!b.body?.trim())return NextResponse.json({error:"제목과 내용을 입력해주세요."},{status:400}); if(b.targetScope==="grade"&&!b.targetGrade)return NextResponse.json({error:"대상 학년을 선택해주세요."},{status:400}); if(b.targetScope==="student"&&!b.studentId)return NextResponse.json({error:"대상 학생을 선택해주세요."},{status:400});
 const admin=createAdminClient(); const uploaded:string[]=[]; try{ for(const f of files){const v=validatePdf({originalFilename:f.originalFilename,mimeType:f.mimeType,sizeBytes:Number(f.sizeBytes)}); if(!v.ok)throw new Error(v.error); if(!String(f.storagePath||"").startsWith(`${a.user.id}/`))throw new Error("첨부 경로가 올바르지 않습니다."); const {data,error}=await admin.storage.from(NOTICE_BUCKET).list(String(f.storagePath).split("/")[0],{search:String(f.storagePath).split("/")[1]}); if(error||!data?.length)throw new Error(`${v.filename} 업로드 확인에 실패했습니다.`); uploaded.push(f.storagePath); }
 const {data:notice,error}=await admin.from("notices").insert({type:b.type,title:b.title.trim(),body:b.body.trim(),target_scope:b.targetScope,target_grade:b.targetScope==="grade"?b.targetGrade:null,requires_confirmation:!!b.requiresConfirmation,created_by:a.user.id,published_at:new Date().toISOString()}).select("id,target_scope,target_grade").single(); if(error||!notice)throw new Error("알림 저장에 실패했습니다."); if(b.targetScope==="student"){const {error:le}=await admin.from("notice_students").insert({notice_id:notice.id,student_id:b.studentId}); if(le)throw new Error("학생 대상 연결에 실패했습니다.");}
 if(files.length){const rows=files.map((f:any)=>({notice_id:notice.id,storage_path:f.storagePath,original_filename:f.originalFilename,mime_type:f.mimeType,size_bytes:f.sizeBytes,uploaded_by:a.user.id})); const {error:ae}=await admin.from("notice_attachments").insert(rows); if(ae)throw new Error("첨부파일 기록에 실패했습니다.");}
 const push=await sendNoticePushes(notice); return NextResponse.json({noticeId:notice.id,message:"공지가 게시되었습니다.",push}); }catch(e){ if(uploaded.length) await admin.storage.from(NOTICE_BUCKET).remove(uploaded); return NextResponse.json({error:e instanceof Error?e.message:"게시 중 오류가 발생했습니다."},{status:400});}}
