import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { sendNoticePushes } from "@/lib/push/send";
import { buildWarningNotice, changeType } from "@/lib/warnings/format";
import type { WarningCellChange } from "@/lib/warnings/types";
export const runtime = "nodejs";
async function staff(){const s=await createClient();const {data:{user}}=await s.auth.getUser();if(!user)return{e:NextResponse.json({error:"세션이 만료되었습니다. 다시 로그인해 주세요."},{status:401})};const {data:p}=await s.from("profiles").select("role").eq("id",user.id).single();if(!["admin","teacher"].includes(p?.role))return{e:NextResponse.json({error:"교사 또는 관리자 권한이 필요합니다."},{status:403})};return{user};}
function monthTotal(entries:any[], studentId:string, month:number){return entries.filter(e=>e.student_id===studentId&&e.month===month).reduce((s,e)=>s+Number(e.delta||0),0)}
export async function POST(req:Request){const a=await staff();if("e"in a)return a.e;const b=await req.json();const changes=(Array.isArray(b.changes)?b.changes:[]) as WarningCellChange[];const year=Number(b.academicYear),semester=Number(b.semester),month=Number(b.month);const key=String(b.idempotencyKey||"");if(!key||!year||!semester||!month||!changes.length)return NextResponse.json({error:"저장할 변경사항을 확인해주세요."},{status:400});
 const admin=createAdminClient();const existing=await admin.from("warning_change_batches").select("id").eq("idempotency_key",key).maybeSingle();if(existing.data)return NextResponse.json({message:"이미 처리된 변경사항입니다.",batchId:existing.data.id,idempotent:true});
 const studentIds=Array.from(new Set(changes.map(c=>c.studentId)));const currentRes=await admin.from("warning_entries").select("student_id,warning_date,entry_type,delta,month").in("student_id",studentIds).eq("academic_year",year).eq("semester",semester);if(currentRes.error&&currentRes.error.code!=="42P01")return NextResponse.json({error:"현재 경고 내역을 확인하지 못했습니다."},{status:500});const current=currentRes.data||[];
 for(const c of changes){const now=current.filter((e:any)=>e.student_id===c.studentId&&e.entry_type===c.entryType&&(c.entryType==="grace_adjustment"?e.month===month:e.warning_date===c.date)).reduce((s:any,e:any)=>s+Number(e.delta||0),0);if(now!==Number(c.previousValue))return NextResponse.json({error:"다른 사용자가 이 경고 내역을 먼저 변경했습니다. 최신 내용을 확인한 후 다시 저장해 주세요."},{status:409});}
 const {data:batch,error:be}=await admin.from("warning_change_batches").insert({idempotency_key:key,academic_year:year,semester,month,author_id:a.user.id}).select("id").single();if(be||!batch)return NextResponse.json({error:"경고 변경 묶음을 저장하지 못했습니다."},{status:500});
 const rows=changes.map(c=>{const delta=Number(c.newValue)-Number(c.previousValue);return{batch_id:batch.id,student_id:c.studentId,warning_date:c.entryType==="daily"?c.date:null,academic_year:year,semester,month,entry_type:c.entryType,change_type:changeType(delta,c.entryType),previous_value:c.previousValue,new_value:c.newValue,delta,parent_visible_reason:c.parentVisibleReason||null,teacher_note:c.teacherNote||null,author_id:a.user.id};}).filter(r=>r.delta!==0);const {error:ee}=await admin.from("warning_entries").insert(rows);if(ee)return NextResponse.json({error:"경고 내역 저장에 실패했습니다."},{status:500});
 const [{data:students},{data:allEntries},{data:links}]=await Promise.all([admin.from("students").select("id,name").in("id",studentIds),admin.from("warning_entries").select("student_id,delta,month").in("student_id",studentIds).eq("academic_year",year).eq("semester",semester),admin.from("parent_students").select("student_id,parent_id").in("student_id",studentIds)]);
 let notices=0,pushSent=0,pushFailed=0,recipients=0;const missing:string[]=[];for(const studentId of studentIds){const student=(students||[]).find((s:any)=>s.id===studentId);const per=changes.filter(c=>c.studentId===studentId);const total=monthTotal(allEntries||[],studentId,month);const content=buildWarningNotice(student?.name||"학생",per,total);const {data:notice,error:ne}=await admin.from("notices").insert({type:"warning",title:content.title,body:content.body,target_scope:"student",requires_confirmation:true,created_by:a.user.id,published_at:new Date().toISOString(),source_type:"warning_update",source_id:batch.id}).select("id,target_scope,target_grade").single();if(ne||!notice)continue;await admin.from("notice_students").insert({notice_id:notice.id,student_id:studentId});const recipientCount=(links||[]).filter((l:any)=>l.student_id===studentId).length;if(!recipientCount)missing.push(studentId);const push=await sendNoticePushes(notice);notices++;recipients+=recipientCount;pushSent+=push.sent;pushFailed+=push.failed;await admin.from("warning_generated_notices").upsert({batch_id:batch.id,student_id:studentId,notice_id:notice.id,recipient_count:recipientCount,push_sent_count:push.sent,push_failed_count:push.failed});}
 if(missing.length)await admin.from("warning_change_batches").update({missing_parent_student_ids:missing}).eq("id",batch.id);return NextResponse.json({message:`${studentIds.length}명의 학생 경고 내역을 저장했습니다. 학부모 알림 ${notices}건이 생성되었고, 푸시 알림 ${pushSent}건이 전송되었습니다.`,batchId:batch.id,notices,recipients,push:{sent:pushSent,failed:pushFailed},missingParentStudentIds:missing});}
