"use client";
import { FormEvent, useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";
function urlBase64ToUint8Array(base64String:string){const padding="=".repeat((4-base64String.length%4)%4);const base64=(base64String+padding).replace(/-/g,"+").replace(/_/g,"/");const raw=atob(base64);return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)));}
export default function AccountSettings({email}:{email:string}){const [cur,setCur]=useState("");const [next,setNext]=useState("");const [confirm,setConfirm]=useState("");const [msg,setMsg]=useState("");const [err,setErr]=useState("");const [busy,setBusy]=useState(false);const [push,setPush]=useState("앱 알림이 꺼져 있습니다.");const [showIos,setShowIos]=useState(false);
useEffect(()=>{if(!("serviceWorker" in navigator)||!("PushManager" in window)||!("Notification" in window)){setPush("이 기기에서는 앱 알림을 지원하지 않습니다.");return;} if(Notification.permission==="denied") setPush("알림 권한이 차단되어 있습니다."); else navigator.serviceWorker.ready.then(r=>r.pushManager.getSubscription()).then(s=>setPush(s?"앱 알림이 켜져 있습니다.":"앱 알림이 꺼져 있습니다."));},[]);
async function change(e:FormEvent){e.preventDefault();setErr("");setMsg(""); if(!cur||!next||!confirm)return setErr("모든 비밀번호 항목을 입력해주세요."); if(next.length<8)return setErr("비밀번호는 8자 이상이어야 합니다."); if(next!==confirm)return setErr("새 비밀번호가 서로 일치하지 않습니다."); if(cur===next)return setErr("새 비밀번호는 현재 비밀번호와 달라야 합니다."); setBusy(true); const s=createClient(); const {error:signErr}=await s.auth.signInWithPassword({email,password:cur}); if(signErr){setErr("현재 비밀번호가 올바르지 않습니다.");setBusy(false);return;} const {error}=await s.auth.updateUser({password:next}); setBusy(false); if(error)setErr("비밀번호 변경에 실패했습니다."); else{setCur("");setNext("");setConfirm("");setMsg("비밀번호가 변경되었습니다.");}}
async function enablePush(){setErr(""); if(!("serviceWorker" in navigator)||!("PushManager" in window)||!("Notification" in window))return setPush("이 기기에서는 앱 알림을 지원하지 않습니다."); const reg=await navigator.serviceWorker.ready; if(Notification.permission!=="granted"){const p=await Notification.requestPermission(); if(p==="denied"){setPush("알림 권한이 차단되어 있습니다.");return;} if(p!=="granted")return;} const key=process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY; if(!key){setErr("VAPID 공개 키가 설정되지 않았습니다.");return;} const sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:urlBase64ToUint8Array(key)}); const res=await fetch("/api/push/subscribe",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(sub)}); setPush(res.ok?"앱 알림이 켜져 있습니다.":"앱 알림이 꺼져 있습니다.");}
async function disablePush(){const reg=await navigator.serviceWorker.ready; const sub=await reg.pushManager.getSubscription(); await fetch("/api/push/subscribe",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({endpoint:sub?.endpoint})}); await sub?.unsubscribe(); setPush("앱 알림이 꺼져 있습니다.");}
return <div className="account-wrap"><section className="form-panel"><p className="eyebrow">ACCOUNT</p><h2>비밀번호 변경</h2><form onSubmit={change}><label>현재 비밀번호</label><input type="password" autoComplete="current-password" value={cur} onChange={e=>setCur(e.target.value)} required/><label>새 비밀번호</label><input type="password" autoComplete="new-password" value={next} onChange={e=>setNext(e.target.value)} required/><label>새 비밀번호 확인</label><input type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} required/><button className="primary" disabled={busy}>{busy?"변경 중...":"비밀번호 변경"}</button></form>{msg&&<p role="status" className="success-message">{msg}</p>}{err&&<p role="alert" className="form-error">{err}</p>}</section><section className="content-card"><p className="eyebrow">PUSH</p><h2>앱 알림 설정</h2><p role="status" className="notice-body">{push}</p><p className="muted">알림은 버튼을 누른 뒤에만 권한을 요청합니다. iPhone/iPad는 공유 → 홈 화면에 추가 후 홈 화면 앱에서 알림을 켜야 합니다. OS, 브라우저, 네트워크 설정에 따라 전달이 보장되지 않으며 앱 안의 읽지 않은 알림이 항상 대체 수단입니다.</p><div className="topbar-actions"><button className="primary" onClick={enablePush}>앱 알림 켜기</button><button className="secondary" onClick={disablePush}>앱 알림 끄기</button><button className="secondary" onClick={()=>setShowIos(!showIos)}>홈 화면 추가 방법 보기</button></div>{showIos&&<ol className="muted"><li>Safari에서 포털을 엽니다.</li><li>공유 버튼을 누릅니다.</li><li>홈 화면에 추가를 선택합니다.</li><li>홈 화면 아이콘으로 다시 열고 앱 알림 켜기를 누릅니다.</li></ol>}</section></div>}
