import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import type { WarningGridStudent } from "@/lib/warnings/types";
export const runtime = "nodejs";
async function auth(){const s=await createClient();const {data:{user}}=await s.auth.getUser();if(!user)return{e:NextResponse.json({error:"세션이 만료되었습니다. 다시 로그인해 주세요."},{status:401})};const {data:p}=await s.from("profiles").select("role").eq("id",user.id).single();if(!["admin","teacher","parent"].includes(p?.role||""))return{e:NextResponse.json({error:"권한을 확인할 수 없습니다."},{status:403})};return{user,role:p?.role,s};}
function monthDates(year:number, month:number){const d=new Date(Date.UTC(year,month-1,1));const a:string[]=[];while(d.getUTCMonth()===month-1){a.push(d.toISOString().slice(0,10));d.setUTCDate(d.getUTCDate()+1);}return a;}
export async function GET(req:Request){const a=await auth();if("e"in a)return a.e;if(!["admin","teacher","parent"].includes(a.role||""))return NextResponse.json({error:"권한이 필요합니다."},{status:403});const url=new URL(req.url);const year=Number(url.searchParams.get("year")||new Date().getFullYear());const semester=Number(url.searchParams.get("semester")||1);const month=Number(url.searchParams.get("month")||new Date().getMonth()+1);const grade=url.searchParams.get("grade")||"";const studentName=url.searchParams.get("student")||"";const dates=monthDates(year,month);
 let studentQ=a.s.from("students").select("id,name,grade,homeroom,active,parent_students(parent_id)").eq("active",true).order("grade").order("name"); if(grade)studentQ=studentQ.eq("grade",grade); if(studentName)studentQ=studentQ.ilike("name",`%${studentName}%`); const {data:students,error:se}=await studentQ; if(se)return NextResponse.json({error:"경고 내역을 불러오는 중 오류가 발생했습니다."},{status:500});
 const ids=(students||[]).map((s:any)=>s.id); let entries:any[]=[]; if(ids.length){const {data,error}=await a.s.from("warning_entries").select("student_id,warning_date,entry_type,delta,created_at,month").in("student_id",ids).eq("academic_year",year).eq("semester",semester); if(error&&error.code!=="42P01")return NextResponse.json({error:error.message},{status:500}); entries=data||[];}
 const rows:WarningGridStudent[]=(students||[]).map((st:any)=>{const daily:Object=Object.fromEntries(dates.map(d=>[d,0]));let grace=0,semesterTotal=0,last:string|null=null;for(const e of entries.filter(x=>x.student_id===st.id)){if(e.entry_type==="daily"&&e.warning_date){if(String(e.warning_date).slice(5,7)===String(month).padStart(2,"0"))(daily as any)[e.warning_date]=((daily as any)[e.warning_date]||0)+e.delta;semesterTotal+=e.delta;}else{if(e.month===month)grace+=e.delta;semesterTotal+=e.delta;}if(!last||e.created_at>last)last=e.created_at;}const monthlyTotal=Object.values(daily as Record<string,number>).reduce((s,n)=>s+n,0)+grace;return{id:st.id,name:st.name,grade:st.grade,homeroom:st.homeroom,parentCount:Array.isArray(st.parent_students)?st.parent_students.length:0,daily:daily as Record<string,number>,graceAdjustment:grace,monthlyTotal,semesterTotal,lastUpdatedAt:last};});
 return NextResponse.json({dates,students:rows,grades:Array.from(new Set((students||[]).map((s:any)=>s.grade))).sort()});}
